scarab_stats/README.md, scarab_stats/scarab_stats.py
Squashed all previous commits into one, and added write protect to non-derived stats. Derived stats can be overwritten if they already exist, and an optional parameter (overwrite) can be used to turn on a safety net if this behaviour is not desired. These changes are documented in the README.
=> Allows overwrite of derived stats

common/Dockerfile.common, run_clustering.sh, run_exp_using_descriptor.py, run_scarab_allbench.sh, run_scarab_mode_4_allbench.sh, run_simpoint_trace.sh, setup_apps.sh, spec2017/install.sh
Flow 2 does the following:
1. Traces the application. The output is one big trace
2. Processes the big trace, generates the fingerprints, and runs the clustering. The output is the simpoints.
3. Extracts the simpoint traces from the one big trace. The output is the simpoint traces
Flow 2 relies on a DynamoRIO feature that it internally divides the one big trace into smaller chunks with a given size. By setting the chunk size to the simpoint size, the fingerprint generations can be done in parallel where each task targets a single chunk. And later we can easily separate the simpoints traces from the big trace.
It is important that the fingerprint generation (as well as scarab simulation) uses the same way of counting instructions as how DynamoRIO does it while generating chunks, which is …
=> Modify simpoint flow 1 and its simulation based on SPEC

scarab_stats/README.md, scarab_stats/scarab_stats.py
Changed `derive_stat` to weight and aggregate simpoints before computing `equation`. This can be disabled by setting the `agg_first` optional argument to false. Since data is stored internally as a pandas dataframe with a column per simpoint, each simpoint's entry contains the same (duplicated) values for their respective workload. This means that all simpoints for a given workload&config will have the same value. Using graphing functions which aggregate simpoints is not an issue, since weights sum to zero.
Example:
| Workload Config Simpoint | Value of derived stat | weight |
| -------- | ------- | ------- | 
| Mysql Baseline 4 | 300 | 70% |
| Mysql Baseline 10 | 300 | 30% |
When graphing derived stat: 300\*0.7 + 300\*0.3 = 300
=> Changed derive stat to weight simpoints at derive time by default

README.LitzLab.md, README.md, common/Dockerfile.common, run.sh
Disabling ASLR while building an image is not possible; containers share the setting with the host: https://stackoverflow.com/questions/54845095/cannot-run-sysctl-command-in-dockerfile
This commit turns off ASLR before running the simpoint script; the user needs to recover the setting afterwards manually.
=> remove disabling ASLR from docker build as it faults

scripts/local_runner.py, scripts/slurm_runner.py, scripts/utilities.py
The full stack print on an exception will ease debugging.
=> Add printing trace stack on an exception

scarab_stats/README.md, scarab_stats/scarab_stats.py, scarab_stats/scarab_stats_quick_start.ipynb
Modified stats file loading to account for new group id column. Added code to calculate distribution data for each stat group and calculate IPC. Also updated the search path for simpoint data to work with updated infrastructure
NOTE: Requires Scarab repository patch to add group id column. Currently approved but not merged (`group_names`)
=> Added support for group stat generation and supported new infrastructure

run.sh
Skipping local docker image build process, if we found a pre-build docker image which is matching to the commit hash from github package(automatically generated image based on the commit hash).
=> Use a prebuilt DockerHub image instead of building locally

common/Dockerfile.common
- The public scarab is now buildable with g++-11
=> No need to use g++-9

scripts/local_runner.py, scripts/run_simulation.py, scripts/run_trace.py, scripts/slurm_runner.py, scripts/utilities.py
- Directly execute it within the command for non-interactive tracing/simulation
- Remove bashrc modification from non-interactive tracing/simulation
- Only an interactive shell needs to modify bashrc
=> Append 'source /usr/local/bin/user_entrypoint.sh' to .bashrc only for the interactive shell

scripts/slurm_runner.py
Previous logic for checking which image is available on a node did not detect that it was not available, causing runs to fail on that node. Logic for checking which simulations are running always printed running even if no simulations were running.
=> Small Fixes to Slurm Runner

scripts/utilities.py
Hi, @5surim 
I realized I had a typo at "trace_then_clustering"  logic at the previous iterative trace commit.
I checked the normal working with "trace_then_clustering" & "iterative" with this correction.
Thanks.
Best regards
=> Fix typo from the autoware trace commit

common/scripts/run_simpoint_trace.py, workloads/autoware/workload_user_entrypoint.sh, workloads/workloads_db.json
I made some changes to the iterative tracing sequence due to issues with running the simulation:
1. Renamed folders to follow the "Timestep_#" format before running raw2trace.
2. Updated the yabloc tracing folder.
3. Set a limit on the maximum process count during the raw2trace stage.
=> Fix folder renaming timing for iterative tracing

scripts/utilities.py, workloads/workloads_db.json
nine geekbench workloads got wrong trim_type when they were traced
=> trim_type is written incorrect in finish_trace

run.sh, scripts/run_perf.py, scripts/run_simulation.py, scripts/run_trace.py, scripts/utilities.py
- only remove the container when the last shell exits
only affect --run
* you can run multiple `./run.sh --run <your_experiment>` commands (interactive shell) to log into a single container.
=> Allow multiple interactive shells attached to a single container

scarab_stats/scarab_stats.py
Fixed error in retrieving stats that would occur when one config's name was a subset of another config, causing aggregation errors while plotting
Ex:
FDIP would also match Ideal_FDIP, and the weights of both runs would sum to 2.0
=> Stat retreive fix

scripts/slurm_runner.py
The previous check for the docker image looked at all slurm nodes, which caused the script to fail if a node did not have docker installed. The fixed check only looks for the image on available nodes, which have already been checked for docker.
=> [FIX] Only check available nodes for docker image

README.md
@Kiminje There was a typo in the instructions. please check this out
=> Fix typo in the debugging instructions

scripts/utilities.py
This will allow running additional configurations within the same experiment directory
while it still checks if the scarab binary is busy when the binary is updated.
=> copy scarab binary only when the src/dest binaries differ or no dest binary eixsts

README.md, scripts/local_runner.py, scripts/slurm_runner.py, scripts/utilities.py
`docker pull` command became not working without proper permission setup after `Docker Image Manifest V2`.
Fix:
1. Instructions to correctly setup the requirement based on the [GitHub Doc `Working with the Container registry`](https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry).
2. Check the output of `docker pull` command and handle it properly. Only build a new image when it is not available by `docker pull`
=> Add an instruction for proper 'docker pull' and fix for it

README.md, quickstart_env.yaml
non-stats-lib python scripts have been running without conda venv on our machines.
This PR integrates the package versions to make all the Python scripts we have work within a single virtual environment.
=> Fix quickstart_env.yaml for non-stats-lib python scripts

scripts/slurm_runner.py, scripts/utilities.py
image_exist function bug fix
The image_exist implementation didn't cover the slurm use-cases.
If "docker pull fail" occurs, we should run the image_check function to the target_node, not local.
=> Fix a bug on the image_exist exception handler

scripts/utilities.py
I think we need more detailed exception msg, when we don't have a proper docker image for generating container.
As-is
```shell
Traceback (most recent call last):
File "/soe/mkim293/seop/scarab-infra/scripts/slurm_runner.py", line 416, in run_simulation
scarab_githash = prepare_simulation(user, scarab_path, scarab_build, descriptor_data['root_dir'], experiment_name, architecture, docker_prefix, githash, infra_dir, False, dbg_lvl)^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/soe/mkim293/seop/scarab-infra/scripts/utilities.py", line 254, in prepare_simulation
raise e
File "/soe/mkim293/seop/scarab-infra/scripts/utilities.py", line 183, in prepare_simulation …
```
=> Add more detailed exception msg

.github/workflows/docker-image.yml
Since https://github.com/litz-lab/scarab-infra/pull/158, we have never executed the command (docker build) within the workflow. https://github.com/litz-lab/scarab-infra/pull/158 made the workflow only build the image when we find the changes within ./common.
https://github.com/litz-lab/scarab-infra/pull/160 first tried to build the image within the workflow, and it failed due to a missing `|` for the command with the line breaks.
Before that, I used the single-line command instead of with the line break. The line break requires | for the run part.
=> Fix for a workflow error

json/top_simpoint.json
`warmup` key has been introduced in https://github.com/litz-lab/scarab-infra/pull/177
Add a missing key in `top_simpoint.json` not only in `exp.json`.
This change will make the scarab workflow run 50M warmup and 10M warmup.
The trace itself (release - top_simpoint_traces.tar.gz) has been updated already.
=> Add a missing warmup field update in top_simpoint.json
